### ISSUE TITLE
"overrideAttachToTangle" and "setSettings" is not overriding IRI "attachToTangle" command.

### ISSUE THREAD

**Issue by pasupulaphani** [iotaledger/iota.js#323] opened 2018-12-15 15:48 UTC
### Bug description
Cannot override function "attachToTangle" with API methods ```overrideAttachToTangle``` and ```setSettings```. This is on iota.js beta-6

### Steps To Reproduce
1. iota = composeAPI({provider: '<your node>'})
2. iota.overrideAttachToTangle(attachToTangle)
3. iota.prepareTransfers(seed, transfers)
4. iota.sendTrytes(trytes, depth, minWeightMagnitude)

### Expected behaviour
When making the transfer it should use the custom function to send IRI "ATTACH_TO_TANGLE" command.

### Actual behavior
The api is not making the IRI command.

### Errors
No errors, but doesn't behave as expected.

**Comment by chrisdukakis** [comment] 2018-12-15 19:09
Hi @pasupulaphani , I can't repro this issue. Could you post `attachToTangle` function from step 2.?

**Comment by gillii** [comment] 2019-02-28 16:08
Hey. I think I have the same issue, so I'm going to write about it.

I'm trying to use curl.lib.js to do the POW for a value transaction. My @iota/core is 1.0.0-beta.8, curl.lib.js is 1.0.22. I'm using the devnet with devnet.thetangle.org provider.

### Bug description

After I overrideAttachToTangle with a function, that function never gets called, and iota.js attaches the transactions to the Tangle with the default attachToTangle function with server-side POW.

### Steps To Reproduce

The bug occurs when I first composeAPI without specifying a custom attachToTangle function, then I overrideAttachToTangle like this:

```
import { composeAPI } from "@iota/core";
const iota = composeAPI({
	provider: "https://nodes.devnet.thetangle.org:443"
});

import { init as curlInit, overrideAttachToTangle as curlOverrideAttachToTangle }
	from "curl.lib.js";
curlInit();

// curl.lib.js's overrideAttachToTangle method assigns its own function to api.attachToTangle
curlOverrideAttachToTangle(iota); // so this does this: iota.attachToTangle = (...) => {...}
// But this doesn't work, so I'm going to use @iota/core's overrideAttachToTangle method,
// 	maybe it does something different.

// @iota/core's overrideAttachToTangle needs a function and curl.lib.js doesn't simply give a
// 	function (AFAIK), so I have to do some messy stuff to get a function:
const dummyApi = {
	attachToTangle : function (
		trunkTransaction,
		branchTransaction,
		minWeight,
		trytesArray,
		callback
	) {}
};
curlOverrideAttachToTangle(dummyApi);
iota.overrideAttachToTangle(dummyApi.attachToTangle);

const transfers = [{
  address: "999999999999999999999999999999999999IOTAJSISSUEOVERRIDEATTACHTOTANGLEREPLYGILLIIA",
  value: 0, //1,
  tag: "",
  message: ""
}];
const depth = 3;
const seed = "9999999999999999999999999999999999999IOTAJSISSUEOVERRIDEATTACHTOTANGLEREPLYGILLII";
iota.prepareTransfers(seed, transfers)
	.then((myTrytes) => {
		return iota.sendTrytes(myTrytes, depth, 14);
	});
```

### Actual behaviour

This successfully publishes the transactions to the Tangle, but it does the POW server side, the nonce has POWSRVIO in it (because the provider uses that service to do its POW), curl.lib.js's attachToTangle doesn't get called, the console.logs inside it don't display, there's no GPU activity during the attachments.

### Expected behaviour

After overrideAttachToTangle with a function I expect @iota/core to use that function while attaching to the Tangle.

If I composeApi with settings.attachToTangle specified it actually kinda almost works:

```
import { composeAPI } from "@iota/core";
import { init as curlInit, overrideAttachToTangle as curlOverrideAttachToTangle }
	from "curl.lib.js";
curlInit();

const dummyApi = {
	attachToTangle : function (
		trunkTransaction,
		branchTransaction,
		minWeight,
		trytesArray,
		callback
	) {}
};
curlOverrideAttachToTangle(dummyApi);

const iota = composeAPI({
	provider: "https://nodes.devnet.thetangle.org:443",
	attachToTangle: dummyApi.attachToTangle
});

// prepareTransfers, sendTrytes...
```
So this doesn't work (yet), I still get some errors (I'll mess around with it later, probably I missed something, or 1.0.0-beta and curl.lib.js aren't compatible anymore), but the custom attachToTangle specified in the API constructor actually gets called, the console.logs inside it actually display and I actually see GPU load.

**Comment by chrisdukakis** [comment] 2019-02-28 17:08
Hi @gillii , thanks for posting. I'll investigate.

**Comment by Tsangares** [comment] 2019-03-09 07:55
@chrisdukakis 
I arrived here with the same goals as OP. I think @pasupulaphani would like to know how to override default attachToTangle to do remote POW. If you could explain that would indirectly solve the issue at hand.

**Comment by pasupulaphani** [comment] 2019-03-09 11:51
This worked for me 

‘’’
const { composeAPI } = require('@iota/core')
const iota = composeAPI({
  attachToTangle
})
‘’’

**Comment by obany** [comment] 2021-04-27 12:27
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.

**Closed by obany** 2021-04-27 12:27 UTC
Labels: C - attachToTangle, L - Investigating
